apiVersion: v1
kind: Service
metadata:
  name: image-gallery-service
spec:
  type: LoadBalancer
  selector:
    app: image-gallery
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8080

