name: Deploy to EKS

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      IMAGE_URI: ${{ vars.ECR_REPO }}:${{ vars.IMAGE_TAG }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region ${{ vars.AWS_REGION }} \
            | docker login --username AWS --password-stdin ${{ vars.ECR_REPO }}

      - name: Build, Tag, and Push Docker image
        run: |
          docker build -t image-gallery:${{ vars.IMAGE_TAG }} .
          docker tag image-gallery:${{ vars.IMAGE_TAG }} ${{ env.IMAGE_URI }}
          docker push ${{ env.IMAGE_URI }}

      - name: Update kubeconfig
        run: aws eks update-kubeconfig --name ${{ vars.CLUSTER_NAME }} --region ${{ vars.AWS_REGION }}

      - name: Deploy to EKS
        run: |
          kubectl set image deployment/image-gallery-deployment \
            image-gallery=${{ env.IMAGE_URI }} --record
          kubectl rollout status deployment/image-gallery-deployment
          
